version: "3"
services:
  merklestore:
    build: .
    image: merklestore
    environment:
      - SLEEP_LENGTH=5
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8080:8080
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: "redis:5"
    expose:
      - 6379
